version: '3.5'

x-environment-vars: &environment-vars
  POSTGRES_HOST: postgres
  DATABASE_URL: postgresql://open_event_user:opev_pass@postgres:5432/open_event
  REDIS_URL: redis://redis:6379/0
  ADMIN_EMAIL: "@{ADMIN_EMAIL}"
  ADMIN_PASSWORD: "@{ADMIN_PASSWORD}"

x-defaults: &defaults
  image: eventyay/open-event-server:master
  restart: unless-stopped
  env_file:
    - .env
  environment:
    <<: *environment-vars
  depends_on:
    - postgres
    - redis
  volumes:
    - ./static:/data/app/static
    - ./generated:/data/app/generated # Workaround for #6155

services:

  postgres:
    image: postgis/postgis:12-3.0-alpine
    container_name: opev-postgres
    restart: unless-stopped
    volumes:
      - pg:/var/lib/postgresql/data
      - ./seed:/var/log/seed
    environment:
      POSTGRES_USER: open_event_user
      POSTGRES_PASSWORD: opev_pass
      POSTGRES_DB: open_event
      APP_CONFIG: config.DevelopmentConfig
    networks:
      - oesnet

  redis:
    image: redis:3-alpine
    container_name: opev-redis
    restart: unless-stopped
    command: redis-server
    volumes:
      - rd:/var/lib/redis/data
    networks:
      - oesnet

  web:
    <<: *defaults
    container_name: opev-web
    networks:
      - oesnet


volumes:
    pg:
      external: true
    rd:
      external: true
  
networks:
  oesnet:
    external: yes
